<<<<<<< HEAD
import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.scss";


export default function Home() {
  return (
    <div>
      <Head>
        <title>稀土掘金</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.head}></div>
        <div className={styles.description}>
          <div className={styles.zj}>
          <a href="#" className={styles.item}>
            <div>
              <span>综合</span>
            </div>
          </a>
          <a href="#" className={styles.item}>
            <div>
              <span>关注</span>
            </div>
          </a>
          <a href="#" className={styles.item}>
            <div>
              <span>后端</span>
            </div>
          </a>
          <a href="#" className={styles.item}>
            <div>
              <span>前端</span>
            </div>
          </a>
          <a href="#" className={styles.item}>
            <div>
              <span>Android</span>
            </div>
          </a>
          <a href="#" className={styles.item}>
            <div>
              <span>iOS</span>
            </div>
          </a>
          <a href="#" className={styles.item}>
            <div>
              <span>人工智能</span>
            </div>
          </a>
          <a href="#" className={styles.item}>
            <div>
              <span>开发工具</span>
            </div>
          </a>
          <a href="#" className={styles.item}>
            <div>
              <span>代码人生</span>
            </div>
          </a>
          <a href="#" className={styles.item}>
            <div>
              <span>阅读</span>
            </div>
          </a>
          </div>
        </div>
        
        <div className={styles.zhuti}>
          <div className={styles.zuoce}>
            {/* 头部部分 */}
           <div className={styles.listHd}>
            <ul>
            <li><a href="#">推荐</a>|</li>
            <li><a href="#">最新</a>|</li>
            <li><a href="#">热榜</a>|</li>
            </ul>
            </div>

          {/* 主要部分 */}
           <div className={styles.zhuyao}>
              <div className={styles.zhuyaoHd}>
                <div className={styles.zhuyaoName}><a href="#">赵小饼</a></div>
                <div className={styles.zhuyaoXian}></div>
                <div className={styles.zhuyaoTime}>18小时前</div>
              </div>

              <h4><a href="#">掘金会员专属活动来啦！源码共度第一期上线</a></h4>

              <div className={styles.zhuyaoText}>
                Hello,各位会员们好，小饼这次带来了专属年度会员的活动~和若川、张师傅一起来阅读源码吧！Hello,各位会员们好，小饼这次带来了专属年度会员的活动~和若川、张师傅一起来阅读源码吧！
              </div>

           </div>
           <div className={styles.zhuyao}>
              <div className={styles.zhuyaoHd}>
                <div className={styles.zhuyaoName}><a href="#">赵小饼</a></div>
                <div className={styles.zhuyaoXian}></div>
                <div className={styles.zhuyaoTime}>18小时前</div>
              </div>

              <h4><a href="#">掘金会员专属活动来啦！源码共度第一期上线</a></h4>

              <div className={styles.zhuyaoText}>
                Hello,各位会员们好，小饼这次带来了专属年度会员的活动~和若川、张师傅一起来阅读源码吧！Hello,各位会员们好，小饼这次带来了专属年度会员的活动~和若川、张师傅一起来阅读源码吧！
              </div>

           </div>
           <div className={styles.zhuyao}>
              <div className={styles.zhuyaoHd}>
                <div className={styles.zhuyaoName}><a href="#">赵小饼</a></div>
                <div className={styles.zhuyaoXian}></div>
                <div className={styles.zhuyaoTime}>18小时前</div>
              </div>

              <h4><a href="#">掘金会员专属活动来啦！源码共度第一期上线</a></h4>

              <div className={styles.zhuyaoText}>
                Hello,各位会员们好，小饼这次带来了专属年度会员的活动~和若川、张师傅一起来阅读源码吧！Hello,各位会员们好，小饼这次带来了专属年度会员的活动~和若川、张师傅一起来阅读源码吧！
              </div>

           </div>
           <div className={styles.zhuyao}>
              <div className={styles.zhuyaoHd}>
                <div className={styles.zhuyaoName}><a href="#">赵小饼</a></div>
                <div className={styles.zhuyaoXian}></div>
                <div className={styles.zhuyaoTime}>18小时前</div>
              </div>

              <h4><a href="#">掘金会员专属活动来啦！源码共度第一期上线</a></h4>

              <div className={styles.zhuyaoText}>
                Hello,各位会员们好，小饼这次带来了专属年度会员的活动~和若川、张师傅一起来阅读源码吧！Hello,各位会员们好，小饼这次带来了专属年度会员的活动~和若川、张师傅一起来阅读源码吧！
              </div>

           </div>
           <div className={styles.zhuyao}>
              <div className={styles.zhuyaoHd}>
                <div className={styles.zhuyaoName}><a href="#">赵小饼</a></div>
                <div className={styles.zhuyaoXian}></div>
                <div className={styles.zhuyaoTime}>18小时前</div>
              </div>

              <h4><a href="#">掘金会员专属活动来啦！源码共度第一期上线</a></h4>

              <div className={styles.zhuyaoText}>
                Hello,各位会员们好，小饼这次带来了专属年度会员的活动~和若川、张师傅一起来阅读源码吧！Hello,各位会员们好，小饼这次带来了专属年度会员的活动~和若川、张师傅一起来阅读源码吧！
              </div>

           </div>
          </div>
        </div>
      </main>
    </div>
  );
=======
import React, { useEffect, useState } from "react";
import { LOCALDOMAIN } from "@/utils";
import { IArticleIntro } from "./api/articleIntro";
import HOC from "@/components/Ifinitlist/HOC";
import Mock from "mockjs";
import axios from "axios";
import { NextPage } from "next";

interface IProps {
  title: string;
  description: string;
  articles: {
    list: {
      label: string;
      info: string;
      link: string;
    }[];
    total: number;
  };
>>>>>>> upstream/dev
}

// 子组件
const Item: React.FC<{ content: any; index?: number }> = ({
  content,
  index,
}) => {
  return (
    <div
      style={{
        // display: "flex",
        // flexDirection: "column",
        alignItems: "center",
        padding: 5,
        height: "140px",
        backgroundColor: "rgb(255, 255, 255)",
        borderBottom: `1px solid var(--juejin-font-4)`,
      }}
      key={index}
      onClick={(): void => {
        window.open(content.link, "blank", "noopener=yes, noreferrer=yes");
      }}
    >
      {/* <Image src={img} height={60} alt="" />
      列表{id} */}
      <div
        className="article__inform"
        style={{
          fontSize: "12px",
          lineHeight: "normal",
          marginBottom: "8px",
        }}
      >
        掘金酱 | 2个月前
      </div>
      <div>
        <h2
          style={{
            fontSize: "16px",
            lineHeight: "24px",
            color: "#1d2129",
            marginBottom: "8px",
          }}
        >
          列表{index}
        </h2>
        <div
          className="article__inform"
          style={{
            fontSize: "13px",
            lineHeight: "22px",
            color: "rgb(134, 144, 156)",
            marginBottom: "20px",
          }}
        >
          {content.info}
        </div>
        <div>
          <ul className="action-list">
            <li className="item">
              <i className="eye"></i>
              <span>15</span>
            </li>
            <li className="item">
              <i className="zan"></i>
              <span>20</span>
            </li>
            <li className="item">
              <i className="cloud"></i>
              <span>6</span>
            </li>
          </ul>
        </div>
      </div>
    </div>
  );
};

const ItemHoc = HOC(Item);

const Index: NextPage<IProps> = ({ title, description, articles }) => {
  const [content, setContent] = useState(articles);
  const [list, setList] = useState<Array<number>>([]);

  useEffect(() => {
    let arr: any[] = [];
    // 用CMS模拟发布的6篇文章
    for (let i = 0; i < 100; i++) {
      let count = i % 6;

      arr.push({
        id: i,
        content: content.list[count],
      });
    }
    setList(arr);
  }, []);

  return (
    <div>
      <ItemHoc list={list} />
    </div>
  );
};

Index.getInitialProps = async (context) => {
  const { data: homeData } = await axios.get(`${LOCALDOMAIN}/api/home`);
  const { data: articleData } = await axios.post(
    `${LOCALDOMAIN}/api/articleIntro`,
    {
      pageNo: 1,
      pageSize: 6,
    }
  );
  return {
    title: homeData.title,
    description: homeData.description,
    articles: {
      list: articleData.list.map((item: IArticleIntro) => {
        return {
          label: item.label,
          info: item.info,
          link: `${LOCALDOMAIN}/article/${item.articleId}`,
        };
      }),
      total: articleData.total,
    },
  };
};
export default Index;
