import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.scss";


export default function Home() {
  return (
    <div>
      <Head>
        <title>稀土掘金</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.head}></div>
        <div className={styles.description}>
          <div className={styles.zj}>
          <a href="#" className={styles.item}>
            <div>
              <span>综合</span>
            </div>
          </a>
          <a href="#" className={styles.item}>
            <div>
              <span>关注</span>
            </div>
          </a>
          <a href="#" className={styles.item}>
            <div>
              <span>后端</span>
            </div>
          </a>
          <a href="#" className={styles.item}>
            <div>
              <span>前端</span>
            </div>
          </a>
          <a href="#" className={styles.item}>
            <div>
              <span>Android</span>
            </div>
          </a>
          <a href="#" className={styles.item}>
            <div>
              <span>iOS</span>
            </div>
          </a>
          <a href="#" className={styles.item}>
            <div>
              <span>人工智能</span>
            </div>
          </a>
          <a href="#" className={styles.item}>
            <div>
              <span>开发工具</span>
            </div>
          </a>
          <a href="#" className={styles.item}>
            <div>
              <span>代码人生</span>
            </div>
          </a>
          <a href="#" className={styles.item}>
            <div>
              <span>阅读</span>
            </div>
          </a>
          </div>
        </div>
        
        <div className={styles.zhuti}>
          <div className={styles.zuoce}>
            {/* 头部部分 */}
           <div className={styles.listHd}>
            <ul>
            <li><a href="#">推荐</a>|</li>
            <li><a href="#">最新</a>|</li>
            <li><a href="#">热榜</a>|</li>
            </ul>
            </div>

          {/* 主要部分 */}
           <div className={styles.zhuyao}>
              <div className={styles.zhuyaoHd}>
                <div className={styles.zhuyaoName}><a href="#">赵小饼</a></div>
                <div className={styles.zhuyaoXian}></div>
                <div className={styles.zhuyaoTime}>18小时前</div>
              </div>

              <h4><a href="#">掘金会员专属活动来啦！源码共度第一期上线</a></h4>

              <div className={styles.zhuyaoText}>
                Hello,各位会员们好，小饼这次带来了专属年度会员的活动~和若川、张师傅一起来阅读源码吧！Hello,各位会员们好，小饼这次带来了专属年度会员的活动~和若川、张师傅一起来阅读源码吧！
              </div>

           </div>
           <div className={styles.zhuyao}>
              <div className={styles.zhuyaoHd}>
                <div className={styles.zhuyaoName}><a href="#">赵小饼</a></div>
                <div className={styles.zhuyaoXian}></div>
                <div className={styles.zhuyaoTime}>18小时前</div>
              </div>

              <h4><a href="#">掘金会员专属活动来啦！源码共度第一期上线</a></h4>

              <div className={styles.zhuyaoText}>
                Hello,各位会员们好，小饼这次带来了专属年度会员的活动~和若川、张师傅一起来阅读源码吧！Hello,各位会员们好，小饼这次带来了专属年度会员的活动~和若川、张师傅一起来阅读源码吧！
              </div>

           </div>
           <div className={styles.zhuyao}>
              <div className={styles.zhuyaoHd}>
                <div className={styles.zhuyaoName}><a href="#">赵小饼</a></div>
                <div className={styles.zhuyaoXian}></div>
                <div className={styles.zhuyaoTime}>18小时前</div>
              </div>

              <h4><a href="#">掘金会员专属活动来啦！源码共度第一期上线</a></h4>

              <div className={styles.zhuyaoText}>
                Hello,各位会员们好，小饼这次带来了专属年度会员的活动~和若川、张师傅一起来阅读源码吧！Hello,各位会员们好，小饼这次带来了专属年度会员的活动~和若川、张师傅一起来阅读源码吧！
              </div>

           </div>
           <div className={styles.zhuyao}>
              <div className={styles.zhuyaoHd}>
                <div className={styles.zhuyaoName}><a href="#">赵小饼</a></div>
                <div className={styles.zhuyaoXian}></div>
                <div className={styles.zhuyaoTime}>18小时前</div>
              </div>

              <h4><a href="#">掘金会员专属活动来啦！源码共度第一期上线</a></h4>

              <div className={styles.zhuyaoText}>
                Hello,各位会员们好，小饼这次带来了专属年度会员的活动~和若川、张师傅一起来阅读源码吧！Hello,各位会员们好，小饼这次带来了专属年度会员的活动~和若川、张师傅一起来阅读源码吧！
              </div>

           </div>
           <div className={styles.zhuyao}>
              <div className={styles.zhuyaoHd}>
                <div className={styles.zhuyaoName}><a href="#">赵小饼</a></div>
                <div className={styles.zhuyaoXian}></div>
                <div className={styles.zhuyaoTime}>18小时前</div>
              </div>

              <h4><a href="#">掘金会员专属活动来啦！源码共度第一期上线</a></h4>

              <div className={styles.zhuyaoText}>
                Hello,各位会员们好，小饼这次带来了专属年度会员的活动~和若川、张师傅一起来阅读源码吧！Hello,各位会员们好，小饼这次带来了专属年度会员的活动~和若川、张师傅一起来阅读源码吧！
              </div>

           </div>
          </div>
        </div>
      </main>
    </div>
  );
}
